"""Add api_keys table for authentication

Revision ID: 2919e6e03409
Revises: a8e2b505fe67
Create Date: 2025-11-12 00:32:57.120180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2919e6e03409'
down_revision: Union[str, Sequence[str], None] = 'a8e2b505fe67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('last_used_user_agent', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_admin_active', 'api_keys', ['admin_user_id', 'is_active'], unique=False)
    op.create_index('idx_api_keys_expires_active', 'api_keys', ['expires_at', 'is_active'], unique=False)
    op.create_index('idx_api_keys_prefix_active', 'api_keys', ['key_prefix', 'is_active'], unique=False)
    op.create_index('idx_api_keys_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index('idx_api_keys_user_active', table_name='api_keys')
    op.drop_index('idx_api_keys_prefix_active', table_name='api_keys')
    op.drop_index('idx_api_keys_expires_active', table_name='api_keys')
    op.drop_index('idx_api_keys_admin_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
