"""Add additional customer fields for Pennylane

Revision ID: 591f669a8f74
Revises: 20251116233316
Create Date: 2026-01-13 15:25:50.726431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591f669a8f74'
down_revision: Union[str, Sequence[str], None] = '20251116233316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pennylane_customers', sa.Column('delivery_address', sa.String(length=500), nullable=True))
    op.add_column('pennylane_customers', sa.Column('delivery_city', sa.String(length=200), nullable=True))
    op.add_column('pennylane_customers', sa.Column('delivery_postal_code', sa.String(length=20), nullable=True))
    op.add_column('pennylane_customers', sa.Column('delivery_country_code', sa.String(length=10), nullable=True))
    op.add_column('pennylane_customers', sa.Column('reg_no', sa.String(length=50), nullable=True))
    op.add_column('pennylane_customers', sa.Column('recipient', sa.String(length=200), nullable=True))
    op.add_column('pennylane_customers', sa.Column('reference', sa.String(length=100), nullable=True))
    op.add_column('pennylane_customers', sa.Column('external_reference', sa.String(length=100), nullable=True))
    op.add_column('pennylane_customers', sa.Column('billing_language', sa.String(length=10), nullable=True))
    op.add_column('pennylane_customers', sa.Column('payment_conditions', sa.String(length=50), nullable=True))
    op.add_column('pennylane_customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('pennylane_customers', sa.Column('billing_iban', sa.String(length=50), nullable=True))
    op.add_column('pennylane_customers', sa.Column('pennylane_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pennylane_customers', sa.Column('pennylane_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pennylane_customers', 'pennylane_updated_at')
    op.drop_column('pennylane_customers', 'pennylane_created_at')
    op.drop_column('pennylane_customers', 'billing_iban')
    op.drop_column('pennylane_customers', 'notes')
    op.drop_column('pennylane_customers', 'payment_conditions')
    op.drop_column('pennylane_customers', 'billing_language')
    op.drop_column('pennylane_customers', 'external_reference')
    op.drop_column('pennylane_customers', 'reference')
    op.drop_column('pennylane_customers', 'recipient')
    op.drop_column('pennylane_customers', 'reg_no')
    op.drop_column('pennylane_customers', 'delivery_country_code')
    op.drop_column('pennylane_customers', 'delivery_postal_code')
    op.drop_column('pennylane_customers', 'delivery_city')
    op.drop_column('pennylane_customers', 'delivery_address')
    # ### end Alembic commands ###
