"""Add contract_type to contracts

Revision ID: 736c4265309c
Revises: 89e3af466eb3
Create Date: 2026-01-14 13:42:41.935620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736c4265309c'
down_revision: Union[str, Sequence[str], None] = '89e3af466eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    contracttype_enum = sa.Enum('MSP', 'RESELLER', 'END_CUSTOMER', 'OTHER', name='contracttype')
    contracttype_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('contracts', sa.Column('contract_type', contracttype_enum, nullable=False, server_default='OTHER'))
    # Remove the server_default after column is created
    op.alter_column('contracts', 'contract_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'contract_type')
    # Drop the enum type
    sa.Enum(name='contracttype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
