"""Add periodicity fields to contracts

Revision ID: 7db160b68c8f
Revises: c6907407f0af
Create Date: 2026-01-13 19:16:44.067914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db160b68c8f'
down_revision: Union[str, Sequence[str], None] = 'c6907407f0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('periodicity_months', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('value_per_period', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'value_per_period')
    op.drop_column('contracts', 'periodicity_months')
    # ### end Alembic commands ###
