"""Add customer_id to contracts

Revision ID: 89e3af466eb3
Revises: 7db160b68c8f
Create Date: 2026-01-13 19:36:56.236006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e3af466eb3'
down_revision: Union[str, Sequence[str], None] = '7db160b68c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'contracts', 'pennylane_customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_column('contracts', 'customer_id')
    # ### end Alembic commands ###
