"""Make order_id optional and add contract_id to invoices

Revision ID: b04fa3516d42
Revises: 591f669a8f74
Create Date: 2026-01-13 15:39:03.891561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04fa3516d42'
down_revision: Union[str, Sequence[str], None] = '591f669a8f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_contracts_order_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_order_id'), 'contracts', ['order_id'], unique=False)
    op.add_column('pennylane_invoices', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pennylane_invoices_contract_id'), 'pennylane_invoices', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'pennylane_invoices', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pennylane_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_pennylane_invoices_contract_id'), table_name='pennylane_invoices')
    op.drop_column('pennylane_invoices', 'contract_id')
    op.drop_index(op.f('ix_contracts_order_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_order_id'), 'contracts', ['order_id'], unique=True)
    op.alter_column('contracts', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
