"""Add no_contract flag to pennylane_invoices

Revision ID: c6907407f0af
Revises: b04fa3516d42
Create Date: 2026-01-13 19:05:29.400307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6907407f0af'
down_revision: Union[str, Sequence[str], None] = 'b04fa3516d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pennylane_invoices', sa.Column('no_contract', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pennylane_invoices', 'no_contract')
    # ### end Alembic commands ###
